before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/smush
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}}'
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
    # Naming modification from default:
    # - Use dash '-' instead of underscore '_' for better visibility in x86_64 scenario
    # - Remove version from name to simplify bootstrapping
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
